# Generated by Django 2.1.2 on 2018-10-03 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeAccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('request_ip', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('badgeaccess', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='access.BadgeAccess')),
            ],
        ),
    ]
